# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftyGraphDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftyGraphDemo

 pod ‘SwiftyGraph’, :path => '../SwiftyGraph'

  target 'SwiftyGraphDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftyGraphDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
